<tr class="student-row">
      <td><?php the_title();?></td>
      <td><?php the_field('assignment_1');?></td>
      <td><?php the_field('assignment_2');?></td>
      <td><?php the_field('assignment_3');?></td>
      <td><?php the_field('assignment_4');?></td>
      <td><?php the_field('assignment_5');?></td>
      <td><?php the_field('assignment_6');?></td>
      <td><?php the_field('assignment_7');?></td>
      <td><?php the_field('assignment_8');?></td>
      <td><?php the_field('assignment_9');?></td>
      <td><?php the_field('assignment_10');?></td>
      <td><?php the_field('assignment_11');?></td>
      <td><?php the_field('assignment_12');?></td>
      <td><?php the_field('assignment_13');?></td>
      <td><?php the_field('assignment_14');?></td>
      <td><?php the_field('assignment_15');?></td>
      <td><?php the_field('assignment_16');?></td>
      <td><?php the_field('assignment_17');?></td>
      <td><?php the_field('assignment_18');?></td>     
</tr>   